/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Belge 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private Plan _planref; 
		private Yayin _yayinref; 
		private BelgeTur _belgeturref; 
		
		// Properties 
		private DateTime _olusturlmatarih; 
		
		// One-to-many relations 
		private IList<BelgeBireyselKural> _listBelgeBireyselKural;
		private IList<BelgePlanSoruTur> _listBelgePlanSoruTur;
		private IList<BelgeSayfa> _listBelgeSayfa;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Belge()
		{
			_id = 0; 
			_planref = null; 
			_yayinref = null; 
			_belgeturref = null; 
			_olusturlmatarih = DateTime.MinValue; 
			_listBelgeBireyselKural = null; 
			_listBelgePlanSoruTur = null; 
			_listBelgeSayfa = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Belge(long id, Plan planref, Yayin yayinref, BelgeTur belgeturref, DateTime olusturlmatarih)
		{
			_id = id; 
			_planref = planref; 
			_yayinref = yayinref; 
			_belgeturref = belgeturref; 
			_olusturlmatarih = olusturlmatarih; 
			_listBelgeBireyselKural = null; 
			_listBelgePlanSoruTur = null; 
			_listBelgeSayfa = null; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Belgenin üretimine esas Planın Id si
		/// </summary>		
		public virtual Plan PlanRef
		{
			get { return _planref; }
			set { _isChanged |= (_planref != value); _planref = value; }
		} 
	  
		/// <summary>
		/// Belgenin ait olduğu yayının Id si
		/// </summary>		
		public virtual Yayin YayinRef
		{
			get { return _yayinref; }
			set { _isChanged |= (_yayinref != value); _yayinref = value; }
		} 
	  
		/// <summary>
		/// Belgenin Türü (Bireysel Kitap, Günlük Alıştırma, v.b.)
		/// </summary>		
		public virtual BelgeTur BelgeTurRef
		{
			get { return _belgeturref; }
			set { _isChanged |= (_belgeturref != value); _belgeturref = value; }
		} 
	  
		/// <summary>
		/// Belgenin oluşturulduğu tarih
		/// </summary>		
		public virtual DateTime OlusturlmaTarih
		{
			get { return _olusturlmatarih; }
			set { _isChanged |= (_olusturlmatarih != value); _olusturlmatarih = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<BelgeBireyselKural> ListBelgeBireyselKural
		{
			get { return _listBelgeBireyselKural; }
			set { _isChanged |= (_listBelgeBireyselKural != value); _listBelgeBireyselKural = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<BelgePlanSoruTur> ListBelgePlanSoruTur
		{
			get { return _listBelgePlanSoruTur; }
			set { _isChanged |= (_listBelgePlanSoruTur != value); _listBelgePlanSoruTur = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<BelgeSayfa> ListBelgeSayfa
		{
			get { return _listBelgeSayfa; }
			set { _isChanged |= (_listBelgeSayfa != value); _listBelgeSayfa = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Belge castObj = (Belge)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}