/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Figur 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Properties 
		private string _ad; 
		private string _xamlfigur; 
		private byte[] _resimfigur; 
		private string _figurdosyayol; 
		
		// One-to-many relations 
		private IList<VaryansFigur> _listVaryansFigur;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Figur()
		{
			_id = 0; 
			_ad = null; 
			_xamlfigur = null;  
			_resimfigur = null;
			_figurdosyayol = null; 
			_listVaryansFigur = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Figur(long id, string ad, string xamlfigur, byte[] resimfigur, string figurdosyayol)
		{
			_id = id; 
			_ad = ad; 
			_xamlfigur = xamlfigur; 
			_resimfigur = resimfigur; 
			_figurdosyayol = figurdosyayol; 
			_listVaryansFigur = null; 
		}
		
		#endregion // End Full Constructor
		
		#region Required Fields Only Constructor
		
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public Figur(long id, string ad)
		{
			_id = id; 
			_ad = ad; 
			_xamlfigur = null;  
			_resimfigur = null;
			_figurdosyayol = null; 
			_listVaryansFigur = null; 
		}
		
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Figürün Adı
		/// </summary>		
		public virtual string Ad
		{
			get { return _ad; }
			set	
			{
				if ( value != null )
					if( value.Length > 80)
						throw new ArgumentOutOfRangeException("Invalid value for Ad", value, value.ToString());
				
				_isChanged |= (_ad != value); _ad = value;
			}
		} 
	  
		/// <summary>
		/// Figürün XAML formatında olması halinde , saklanacağı alandır.
		/// </summary>		
		public virtual string XamlFigur
		{
			get { return _xamlfigur; }
			set	
			{
				if ( value != null )
					if( value.Length > 2147483647)
						throw new ArgumentOutOfRangeException("Invalid value for XamlFigur", value, value.ToString());
				
				_isChanged |= (_xamlfigur != value); _xamlfigur = value;
			}
		} 
	  
		/// <summary>
		/// Figürün bitmap, jpeg, png olması durumunda saklanacağı yerdir.
		/// </summary>		
		public virtual byte[] ResimFigur
		{
			get { return _resimfigur; }
			set	
			{
				if( value != null && value.Length > 2147483647)
					throw new ArgumentOutOfRangeException("Invalid value for ResimFigur", value, value.ToString());
				
				_isChanged |= (_resimfigur != value); _resimfigur = value;
			}
				
		} 
	  
		/// <summary>
		/// Figürü yerel diskte cache lemek, render performansını arttıracağından figüre ait dosyanın istemci bilgisayarda saklanacağı dosya yoludur.
		/// </summary>		
		public virtual string FigurDosyaYol
		{
			get { return _figurdosyayol; }
			set	
			{
				if ( value != null )
					if( value.Length > 2147483647)
						throw new ArgumentOutOfRangeException("Invalid value for FigurDosyaYol", value, value.ToString());
				
				_isChanged |= (_figurdosyayol != value); _figurdosyayol = value;
			}
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<VaryansFigur> ListVaryansFigur
		{
			get { return _listVaryansFigur; }
			set { _isChanged |= (_listVaryansFigur != value); _listVaryansFigur = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Figur castObj = (Figur)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}