/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Parca 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private Havuz _havuzref; 
		
		// Properties 
		private string _ad; 
		private int _sira; 
		private bool _temelparcami; 
		private string _cerceve; 
		private bool _bireysel; 
		
		// One-to-many relations 
		private IList<Varyans> _listVaryans;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Parca()
		{
			_id = 0; 
			_havuzref = null; 
			_ad = null; 
			_sira = 0; 
			_temelparcami = false; 
			_cerceve = null; 
			_bireysel = false; 
			_listVaryans = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Parca(long id, Havuz havuzref, string ad, int sira, bool temelparcami, string cerceve, bool bireysel)
		{
			_id = id; 
			_havuzref = havuzref; 
			_ad = ad; 
			_sira = sira; 
			_temelparcami = temelparcami; 
			_cerceve = cerceve; 
			_bireysel = bireysel; 
			_listVaryans = null; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Parçanın ait olduğu Havuzun Id si
		/// </summary>		
		public virtual Havuz HavuzRef
		{
			get { return _havuzref; }
			set { _isChanged |= (_havuzref != value); _havuzref = value; }
		} 
	  
		/// <summary>
		/// Parçanın Adı
		/// </summary>		
		public virtual string Ad
		{
			get { return _ad; }
			set	
			{
				if ( value != null )
					if( value.Length > 80)
						throw new ArgumentOutOfRangeException("Invalid value for Ad", value, value.ToString());
				
				_isChanged |= (_ad != value); _ad = value;
			}
		} 
	  
		/// <summary>
		/// Havuzdan bir resim oluştururken ilgili parçanın hangi sırada resimde yer alacağını belirler. Böylece ilgili parça her resimde aynı sırada yer alır. 
		/// </summary>		
		public virtual int Sira
		{
			get { return _sira; }
			set { _isChanged |= (_sira != value); _sira = value; }
		} 
	  
		/// <summary>
		/// Parça ekleme ve parça çıkarma işlemlerinde temel parçalar çıkarılmaz. Yani Temel Parçalar oluşturulan her resimde mutlaka yer alır.
		/// </summary>		
		public virtual bool TemelParcaMi
		{
			get { return _temelparcami; }
			set { _isChanged |= (_temelparcami != value); _temelparcami = value; }
		} 
	  
		/// <summary>
		/// İlgili Parçanın boyut, konum, rotasyon, v.b. ayarları XAML canvas ı şeklinde tutar. İlgili parçaya ait her figürün aynı konuma gelmesini sağlar.
		/// </summary>		
		public virtual string Cerceve
		{
			get { return _cerceve; }
			set	
			{
				if ( value != null )
					if( value.Length > 2147483647)
						throw new ArgumentOutOfRangeException("Invalid value for Cerceve", value, value.ToString());
				
				_isChanged |= (_cerceve != value); _cerceve = value;
			}
		} 
	  
		/// <summary>
		/// Bu parçanın varyansları ve figürleri yoktur. Bu parça sorunun ilgili belgeye eklendiği sırada belirtilen kurallara göre ilgili kişinin resmini tutmak için kullanılır.
		/// </summary>		
		public virtual bool Bireysel
		{
			get { return _bireysel; }
			set { _isChanged |= (_bireysel != value); _bireysel = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<Varyans> ListVaryans
		{
			get { return _listVaryans; }
			set { _isChanged |= (_listVaryans != value); _listVaryans = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Parca castObj = (Parca)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}