/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class PlanSoruTurZorlukAyarZorlukParametre 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private PlanSoruTurZorlukAyar _plansoruturzorlukayarref; 
		private ZorlukParametre _zorlukparametreref; 
		
		// Properties 
		private string _deger; 		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public PlanSoruTurZorlukAyarZorlukParametre()
		{
			_id = 0; 
			_plansoruturzorlukayarref = null; 
			_zorlukparametreref = null; 
			_deger = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public PlanSoruTurZorlukAyarZorlukParametre(long id, PlanSoruTurZorlukAyar plansoruturzorlukayarref, ZorlukParametre zorlukparametreref, string deger)
		{
			_id = id; 
			_plansoruturzorlukayarref = plansoruturzorlukayarref; 
			_zorlukparametreref = zorlukparametreref; 
			_deger = deger; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// PlanSoruTurZorlukAyar tablosunun Id si
		/// </summary>		
		public virtual PlanSoruTurZorlukAyar PlanSoruTurZorlukAyarRef
		{
			get { return _plansoruturzorlukayarref; }
			set { _isChanged |= (_plansoruturzorlukayarref != value); _plansoruturzorlukayarref = value; }
		} 
	  
		/// <summary>
		/// Zorluk Ayarı ile ilişkili Zorluk Parametresinin Id si
		/// </summary>		
		public virtual ZorlukParametre ZorlukParametreRef
		{
			get { return _zorlukparametreref; }
			set { _isChanged |= (_zorlukparametreref != value); _zorlukparametreref = value; }
		} 
	  
		/// <summary>
		/// İlgili zorluk parametresinin değeri. Bu değer Zorluk parametresinin tipine göre cast edilerek kullanılacak.
		/// </summary>		
		public virtual string Deger
		{
			get { return _deger; }
			set	
			{
				if ( value != null )
					if( value.Length > 50)
						throw new ArgumentOutOfRangeException("Invalid value for Deger", value, value.ToString());
				
				_isChanged |= (_deger != value); _deger = value;
			}
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			PlanSoruTurZorlukAyarZorlukParametre castObj = (PlanSoruTurZorlukAyarZorlukParametre)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}