/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class PlanSoruTurZorlukAyar 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private SoruTurZorlukAyar _soruturzorlukayarref; 
		private PlanSoruTur _plansoruturref; 
		
		// One-to-many relations 
		private IList<PlanSoruTurZorlukAyarZorlukParametre> _listPlanSoruTurZorlukAyarZorlukParametre;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public PlanSoruTurZorlukAyar()
		{
			_id = 0; 
			_soruturzorlukayarref = null; 
			_plansoruturref = null; 
			_listPlanSoruTurZorlukAyarZorlukParametre = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public PlanSoruTurZorlukAyar(long id, SoruTurZorlukAyar soruturzorlukayarref, PlanSoruTur plansoruturref)
		{
			_id = id; 
			_soruturzorlukayarref = soruturzorlukayarref; 
			_plansoruturref = plansoruturref; 
			_listPlanSoruTurZorlukAyarZorlukParametre = null; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// İlgili SoruTurZorlukAyar kaydının Id si
		/// </summary>		
		public virtual SoruTurZorlukAyar SoruTurZorlukAyarRef
		{
			get { return _soruturzorlukayarref; }
			set { _isChanged |= (_soruturzorlukayarref != value); _soruturzorlukayarref = value; }
		} 
	  
		/// <summary>
		/// PlanSoruTur Join Tablosunun Id si
		/// </summary>		
		public virtual PlanSoruTur PlanSoruTurRef
		{
			get { return _plansoruturref; }
			set { _isChanged |= (_plansoruturref != value); _plansoruturref = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<PlanSoruTurZorlukAyarZorlukParametre> ListPlanSoruTurZorlukAyarZorlukParametre
		{
			get { return _listPlanSoruTurZorlukAyarZorlukParametre; }
			set { _isChanged |= (_listPlanSoruTurZorlukAyarZorlukParametre != value); _listPlanSoruTurZorlukAyarZorlukParametre = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			PlanSoruTurZorlukAyar castObj = (PlanSoruTurZorlukAyar)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}