/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Plan 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Properties 
		private long _yasgrupref; 
		private string _ad; 
		private DateTime _olusturmatarih; 
		private bool _aktifmi; 
		
		// One-to-many relations 
		private IList<Belge> _listBelge;
		private IList<PlanSoruTur> _listPlanSoruTur;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Plan()
		{
			_id = 0; 
			_yasgrupref = 0; 
			_ad = null; 
			_olusturmatarih = DateTime.MinValue; 
			_aktifmi = false; 
			_listBelge = null; 
			_listPlanSoruTur = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Plan(long id, long yasgrupref, string ad, DateTime olusturmatarih, bool aktifmi)
		{
			_id = id; 
			_yasgrupref = yasgrupref; 
			_ad = ad; 
			_olusturmatarih = olusturmatarih; 
			_aktifmi = aktifmi; 
			_listBelge = null; 
			_listPlanSoruTur = null; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Planın hangi yaş grubuna ait olduğunu belirleyen Yaş gurbu Id si
		/// </summary>		
		public virtual long YasGrupRef
		{
			get { return _yasgrupref; }
			set { _isChanged |= (_yasgrupref != value); _yasgrupref = value; }
		} 
	  
		/// <summary>
		/// Planın adı
		/// </summary>		
		public virtual string Ad
		{
			get { return _ad; }
			set	
			{
				if ( value != null )
					if( value.Length > 80)
						throw new ArgumentOutOfRangeException("Invalid value for Ad", value, value.ToString());
				
				_isChanged |= (_ad != value); _ad = value;
			}
		} 
	  
		/// <summary>
		/// Planın oluşturulduğu tarih
		/// </summary>		
		public virtual DateTime OlusturmaTarih
		{
			get { return _olusturmatarih; }
			set { _isChanged |= (_olusturmatarih != value); _olusturmatarih = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual bool AktifMi
		{
			get { return _aktifmi; }
			set { _isChanged |= (_aktifmi != value); _aktifmi = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<Belge> ListBelge
		{
			get { return _listBelge; }
			set { _isChanged |= (_listBelge != value); _listBelge = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<PlanSoruTur> ListPlanSoruTur
		{
			get { return _listPlanSoruTur; }
			set { _isChanged |= (_listPlanSoruTur != value); _listPlanSoruTur = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Plan castObj = (Plan)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}