/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class SayfaResim 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private Sayfa _sayfaref; 
		
		// Properties 
		private byte[] _resim; 
		private int _resimsayfaindeks; 		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public SayfaResim()
		{
			_id = 0; 
			_sayfaref = null;  
			_resim = null;
			_resimsayfaindeks = 0; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public SayfaResim(long id, Sayfa sayfaref, byte[] resim, int resimsayfaindeks)
		{
			_id = id; 
			_sayfaref = sayfaref; 
			_resim = resim; 
			_resimsayfaindeks = resimsayfaindeks; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Resmin ait olduğu Sayfanın Id si
		/// </summary>		
		public virtual Sayfa SayfaRef
		{
			get { return _sayfaref; }
			set { _isChanged |= (_sayfaref != value); _sayfaref = value; }
		} 
	  
		/// <summary>
		/// Resmin saklandığı alan
		/// </summary>		
		public virtual byte[] Resim
		{
			get { return _resim; }
			set	
			{
				if( value != null && value.Length > 2147483647)
					throw new ArgumentOutOfRangeException("Invalid value for Resim", value, value.ToString());
				
				_isChanged |= (_resim != value); _resim = value;
			}
				
		} 
	  
		/// <summary>
		/// Resmin sayfa şablonunda yer aldığı yere ait indeks
		/// </summary>		
		public virtual int ResimSayfaIndeks
		{
			get { return _resimsayfaindeks; }
			set { _isChanged |= (_resimsayfaindeks != value); _resimsayfaindeks = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			SayfaResim castObj = (SayfaResim)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}