/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Sayfa 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private SayfaTur _sayfaturref; 
		
		// Properties 
		private string _sayfasablon; 
		private DateTime _olusturulmatarih; 
		
		// One-to-many relations 
		private IList<BelgeSayfa> _listBelgeSayfa;
		private IList<SayfaResim> _listSayfaResim;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Sayfa()
		{
			_id = 0; 
			_sayfaturref = null; 
			_sayfasablon = null; 
			_olusturulmatarih = DateTime.MinValue; 
			_listBelgeSayfa = null; 
			_listSayfaResim = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Sayfa(long id, SayfaTur sayfaturref, string sayfasablon, DateTime olusturulmatarih)
		{
			_id = id; 
			_sayfaturref = sayfaturref; 
			_sayfasablon = sayfasablon; 
			_olusturulmatarih = olusturulmatarih; 
			_listBelgeSayfa = null; 
			_listSayfaResim = null; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// İlgili sayfanın tür Id si
		/// </summary>		
		public virtual SayfaTur SayfaTurRef
		{
			get { return _sayfaturref; }
			set { _isChanged |= (_sayfaturref != value); _sayfaturref = value; }
		} 
	  
		/// <summary>
		/// İlgili sayfanın sayfa türüne bağlı olarak üretilmiş, ancak kendisi için özelleştirilmiş xaml şablonu. Her sayfa türü için standart bir şablonu mevcuttur. İlgili sayfa için bu standart şablondaki objelerin tasarımsal değişiklikleri o sayfa için özel olarak bu alanda saklanır. 
		/// </summary>		
		public virtual string SayfaSablon
		{
			get { return _sayfasablon; }
			set	
			{
				if ( value != null )
					if( value.Length > 2147483647)
						throw new ArgumentOutOfRangeException("Invalid value for SayfaSablon", value, value.ToString());
				
				_isChanged |= (_sayfasablon != value); _sayfasablon = value;
			}
		} 
	  
		/// <summary>
		/// Sayfanın oluşturulma tarihi
		/// </summary>		
		public virtual DateTime OlusturulmaTarih
		{
			get { return _olusturulmatarih; }
			set { _isChanged |= (_olusturulmatarih != value); _olusturulmatarih = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<BelgeSayfa> ListBelgeSayfa
		{
			get { return _listBelgeSayfa; }
			set { _isChanged |= (_listBelgeSayfa != value); _listBelgeSayfa = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<SayfaResim> ListSayfaResim
		{
			get { return _listSayfaResim; }
			set { _isChanged |= (_listSayfaResim != value); _listSayfaResim = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Sayfa castObj = (Sayfa)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}