/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class SoruTurZorlukAyar 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private SoruTur _soruturref; 
		private ZorlukAyar _zorlukayarref; 
		
		// One-to-many relations 
		private IList<PlanSoruTurZorlukAyar> _listPlanSoruTurZorlukAyar;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public SoruTurZorlukAyar()
		{
			_id = 0; 
			_soruturref = null; 
			_zorlukayarref = null; 
			_listPlanSoruTurZorlukAyar = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public SoruTurZorlukAyar(long id, SoruTur soruturref, ZorlukAyar zorlukayarref)
		{
			_id = id; 
			_soruturref = soruturref; 
			_zorlukayarref = zorlukayarref; 
			_listPlanSoruTurZorlukAyar = null; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// İlgili soru türünün Id si
		/// </summary>		
		public virtual SoruTur SoruTurRef
		{
			get { return _soruturref; }
			set { _isChanged |= (_soruturref != value); _soruturref = value; }
		} 
	  
		/// <summary>
		/// İlgili Zorluk Ayarının Id si
		/// </summary>		
		public virtual ZorlukAyar ZorlukAyarRef
		{
			get { return _zorlukayarref; }
			set { _isChanged |= (_zorlukayarref != value); _zorlukayarref = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<PlanSoruTurZorlukAyar> ListPlanSoruTurZorlukAyar
		{
			get { return _listPlanSoruTurZorlukAyar; }
			set { _isChanged |= (_listPlanSoruTurZorlukAyar != value); _listPlanSoruTurZorlukAyar = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			SoruTurZorlukAyar castObj = (SoruTurZorlukAyar)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}