/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Soru 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Foreign Keys mappate come Many-To-One 
		private BelgeSayfa _belgesayfaref; 
		private BelgePlanSoruTur _belgeplansoruturref; 
		private SoruTur _soruturref; 
		
		// Properties 
		private int _soruno; 
		private DateTime _uretimtarih; 
		private bool _kullanildimi; 
		
		// One-to-many relations 
		private IList<RefResim> _listRefResim;
		private IList<Secenek> _listSecenek;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Soru()
		{
			_id = 0; 
			_belgesayfaref = null; 
			_belgeplansoruturref = null; 
			_soruturref = null; 
			_soruno = 0; 
			_uretimtarih = DateTime.MinValue; 
			_kullanildimi = false; 
			_listRefResim = null; 
			_listSecenek = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Soru(long id, BelgeSayfa belgesayfaref, BelgePlanSoruTur belgeplansoruturref, SoruTur soruturref, int soruno, DateTime uretimtarih, bool kullanildimi)
		{
			_id = id; 
			_belgesayfaref = belgesayfaref; 
			_belgeplansoruturref = belgeplansoruturref; 
			_soruturref = soruturref; 
			_soruno = soruno; 
			_uretimtarih = uretimtarih; 
			_kullanildimi = kullanildimi; 
			_listRefResim = null; 
			_listSecenek = null; 
		}
		
		#endregion // End Full Constructor
		
		#region Required Fields Only Constructor
		
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public Soru(long id, BelgeSayfa belgesayfaref, BelgePlanSoruTur belgeplansoruturref, SoruTur soruturref, DateTime uretimtarih, bool kullanildimi)
		{
			_id = id; 
			_belgesayfaref = belgesayfaref; 
			_belgeplansoruturref = belgeplansoruturref; 
			_soruturref = soruturref; 
			_soruno = 0; 
			_uretimtarih = uretimtarih; 
			_kullanildimi = kullanildimi; 
			_listRefResim = null; 
			_listSecenek = null; 
		}
		
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Sorunun sahibi olan ilgili belgenin ilgili sayfasının Id si
		/// </summary>		
		public virtual BelgeSayfa BelgeSayfaRef
		{
			get { return _belgesayfaref; }
			set { _isChanged |= (_belgesayfaref != value); _belgesayfaref = value; }
		} 
	  
		/// <summary>
		/// Sorunun hazırlandığı ilgili palana ait ilgili belgenin soru türü ile ilişkili olduğu BelgePlanSoruTur kaydının Id si
		/// </summary>		
		public virtual BelgePlanSoruTur BelgePlanSoruTurRef
		{
			get { return _belgeplansoruturref; }
			set { _isChanged |= (_belgeplansoruturref != value); _belgeplansoruturref = value; }
		} 
	  
		/// <summary>
		/// Sorunun üretildiği Soru Türünün Id si
		/// </summary>		
		public virtual SoruTur SoruTurRef
		{
			get { return _soruturref; }
			set { _isChanged |= (_soruturref != value); _soruturref = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual int SoruNo
		{
			get { return _soruno; }
			set { _isChanged |= (_soruno != value); _soruno = value; }
		} 
	  
		/// <summary>
		/// Sorunun Üretim Tarihi
		/// </summary>		
		public virtual DateTime UretimTarih
		{
			get { return _uretimtarih; }
			set { _isChanged |= (_uretimtarih != value); _uretimtarih = value; }
		} 
	  
		/// <summary>
		/// Sorunun herhangi bir belge kullanılıp kullanılmadığı
		/// </summary>		
		public virtual bool KullanildiMi
		{
			get { return _kullanildimi; }
			set { _isChanged |= (_kullanildimi != value); _kullanildimi = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<RefResim> ListRefResim
		{
			get { return _listRefResim; }
			set { _isChanged |= (_listRefResim != value); _listRefResim = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<Secenek> ListSecenek
		{
			get { return _listSecenek; }
			set { _isChanged |= (_listSecenek != value); _listSecenek = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Soru castObj = (Soru)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}