/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class SoruSablon 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Properties 
		private string _ad; 
		private string _xamlsablon; 
		private bool _bireyselfigurvar; 
		private byte _sablonboyut; 
		private string _aciklama; 
		private byte _refresimadet; 
		private byte _secenekadet; 
		
		// One-to-many relations 
		private IList<SoruTurSoruSablon> _listSoruTurSoruSablon;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public SoruSablon()
		{
			_id = 0; 
			_ad = null; 
			_xamlsablon = null; 
			_bireyselfigurvar = false; 
			_sablonboyut = 0; 
			_aciklama = null; 
			_refresimadet = 0; 
			_secenekadet = 0; 
			_listSoruTurSoruSablon = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public SoruSablon(long id, string ad, string xamlsablon, bool bireyselfigurvar, byte sablonboyut, string aciklama, byte refresimadet, byte secenekadet)
		{
			_id = id; 
			_ad = ad; 
			_xamlsablon = xamlsablon; 
			_bireyselfigurvar = bireyselfigurvar; 
			_sablonboyut = sablonboyut; 
			_aciklama = aciklama; 
			_refresimadet = refresimadet; 
			_secenekadet = secenekadet; 
			_listSoruTurSoruSablon = null; 
		}
		
		#endregion // End Full Constructor
		
		#region Required Fields Only Constructor
		
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public SoruSablon(long id, string ad, string xamlsablon, bool bireyselfigurvar, byte sablonboyut, byte refresimadet, byte secenekadet)
		{
			_id = id; 
			_ad = ad; 
			_xamlsablon = xamlsablon; 
			_bireyselfigurvar = bireyselfigurvar; 
			_sablonboyut = sablonboyut; 
			_aciklama = null; 
			_refresimadet = refresimadet; 
			_secenekadet = secenekadet; 
			_listSoruTurSoruSablon = null; 
		}
		
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Soru Şablonun Adı
		/// </summary>		
		public virtual string Ad
		{
			get { return _ad; }
			set	
			{
				if ( value != null )
					if( value.Length > 80)
						throw new ArgumentOutOfRangeException("Invalid value for Ad", value, value.ToString());
				
				_isChanged |= (_ad != value); _ad = value;
			}
		} 
	  
		/// <summary>
		/// Soruların, belgelerde hangi sayfa düzeniyle yer alacağını belirleyen XAML şablonların saklandığı yerdir. XAML şablonunda şablonun kapladığı alanı betimleyen xaml tanımları bulunur.
		/// </summary>		
		public virtual string XamlSablon
		{
			get { return _xamlsablon; }
			set	
			{
				if ( value != null )
					if( value.Length > 2147483647)
						throw new ArgumentOutOfRangeException("Invalid value for XamlSablon", value, value.ToString());
				
				_isChanged |= (_xamlsablon != value); _xamlsablon = value;
			}
		} 
	  
		/// <summary>
		/// Şablonda bireysel figür olup olmadığına ait değerdir. Eğer soru şablonunda bireysel figür varsa, (sorudaki bireysel figürler haricinde) belgenin hazrılandığı ilgili kişiye ait resim ayrıca soru şablonunda da yer alır.
		/// </summary>		
		public virtual bool BireyselFigurVar
		{
			get { return _bireyselfigurvar; }
			set { _isChanged |= (_bireyselfigurvar != value); _bireyselfigurvar = value; }
		} 
	  
		/// <summary>
		/// Şablonun kapladığı alanı tanımlamak için kullanılır. bir soru şablonu, sayfanın bir bölümünü, bir sayfanın tamamını ve birden fazla sayfayı kaplayabilir. 
		/// </summary>		
		public virtual byte SablonBoyut
		{
			get { return _sablonboyut; }
			set { _isChanged |= (_sablonboyut != value); _sablonboyut = value; }
		} 
	  
		/// <summary>
		/// Soru Şablonu ile ilgili genel açıklamalar.
		/// </summary>		
		public virtual string Aciklama
		{
			get { return _aciklama; }
			set	
			{
				if ( value != null )
					if( value.Length > 2147483647)
						throw new ArgumentOutOfRangeException("Invalid value for Aciklama", value, value.ToString());
				
				_isChanged |= (_aciklama != value); _aciklama = value;
			}
		} 
	  
		/// <summary>
		/// Şablondaki Referans Resim adedi
		/// </summary>		
		public virtual byte RefResimAdet
		{
			get { return _refresimadet; }
			set { _isChanged |= (_refresimadet != value); _refresimadet = value; }
		} 
	  
		/// <summary>
		/// Şablonda yer alan seçenek adedi
		/// </summary>		
		public virtual byte SecenekAdet
		{
			get { return _secenekadet; }
			set { _isChanged |= (_secenekadet != value); _secenekadet = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<SoruTurSoruSablon> ListSoruTurSoruSablon
		{
			get { return _listSoruTurSoruSablon; }
			set { _isChanged |= (_listSoruTurSoruSablon != value); _listSoruTurSoruSablon = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			SoruSablon castObj = (SoruSablon)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}