/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class Yayin 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Properties 
		private int _sayi; 
		private DateTime _tarih; 
		private string _aciklama; 
		
		// One-to-many relations 
		private IList<Belge> _listBelge;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public Yayin()
		{
			_id = 0; 
			_sayi = 0; 
			_tarih = DateTime.MinValue; 
			_aciklama = null; 
			_listBelge = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public Yayin(long id, int sayi, DateTime tarih, string aciklama)
		{
			_id = id; 
			_sayi = sayi; 
			_tarih = tarih; 
			_aciklama = aciklama; 
			_listBelge = null; 
		}
		
		#endregion // End Full Constructor
		
		#region Required Fields Only Constructor
		
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public Yayin(long id, int sayi, DateTime tarih)
		{
			_id = id; 
			_sayi = sayi; 
			_tarih = tarih; 
			_aciklama = null; 
			_listBelge = null; 
		}
		
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Yayının sayısı
		/// </summary>		
		public virtual int Sayi
		{
			get { return _sayi; }
			set { _isChanged |= (_sayi != value); _sayi = value; }
		} 
	  
		/// <summary>
		/// yayınlanma tarihi
		/// </summary>		
		public virtual DateTime Tarih
		{
			get { return _tarih; }
			set { _isChanged |= (_tarih != value); _tarih = value; }
		} 
	  
		/// <summary>
		/// yayına ilişkin genel açıklama
		/// </summary>		
		public virtual string Aciklama
		{
			get { return _aciklama; }
			set	
			{
				if ( value != null )
					if( value.Length > 500)
						throw new ArgumentOutOfRangeException("Invalid value for Aciklama", value, value.ToString());
				
				_isChanged |= (_aciklama != value); _aciklama = value;
			}
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<Belge> ListBelge
		{
			get { return _listBelge; }
			set { _isChanged |= (_listBelge != value); _listBelge = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Yayin castObj = (Yayin)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}