/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace BilisselBeceriler.Entities.Windows
{
	/// <summary>
	/// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
	/// </summary>
	[Serializable]
	public class ZorlukAyar 
	{
		#region Private Members
		
		// Variabili di stato
		private bool _isChanged;
		private bool _isDeleted;

		// Primary Key(s) 
		private long _id; 
		
		// Properties 
		private string _ad; 
		
		// One-to-many relations 
		private IList<SoruTurZorlukAyar> _listSoruTurZorlukAyar;
		private IList<ZorlukParametre> _listZorlukParametre;		

		#endregion
		
		#region Default ( Empty ) Class Constructor
		
		/// <summary>
		/// default constructor
		/// </summary>
		public ZorlukAyar()
		{
			_id = 0; 
			_ad = null; 
			_listSoruTurZorlukAyar = null; 
			_listZorlukParametre = null; 
		}
		
		#endregion // End of Default ( Empty ) Class Constructor
		
		#region Full Constructor
		
		/// <summary>
		/// full constructor
		/// </summary>
		public ZorlukAyar(long id, string ad)
		{
			_id = id; 
			_ad = ad; 
			_listSoruTurZorlukAyar = null; 
			_listZorlukParametre = null; 
		}
		
		#endregion // End Full Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual long Id
		{
			get { return _id; }
			set { _isChanged |= (_id != value); _id = value; }
		} 
	  
		/// <summary>
		/// Zorluk Ayar parametresinin Adı. (Parça Ekle, Parça Çıkar, Şekil Değiştir, v.b.)
		/// </summary>		
		public virtual string Ad
		{
			get { return _ad; }
			set	
			{
				if ( value != null )
					if( value.Length > 80)
						throw new ArgumentOutOfRangeException("Invalid value for Ad", value, value.ToString());
				
				_isChanged |= (_ad != value); _ad = value;
			}
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<SoruTurZorlukAyar> ListSoruTurZorlukAyar
		{
			get { return _listSoruTurZorlukAyar; }
			set { _isChanged |= (_listSoruTurZorlukAyar != value); _listSoruTurZorlukAyar = value; }
		} 
	  
		/// <summary>
		/// 
		/// </summary>		
		public virtual IList<ZorlukParametre> ListZorlukParametre
		{
			get { return _listZorlukParametre; }
			set { _isChanged |= (_listZorlukParametre != value); _listZorlukParametre = value; }
		} 
	  
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		#region Public Functions

		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		#region Equals And HashCode Overrides
		
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			ZorlukAyar castObj = (ZorlukAyar)obj; 
			return ( castObj != null ) &&
				( this._id == castObj.Id );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{ 
			int hash = 57; 
			hash = 27 * hash * this._id.GetHashCode();
					
			return hash;		
			
		}
		
		#endregion
		
	}
}